spring:
  liquibase:
    change-log: 'classpath:db/changelog/master.xml'
    url: 'jdbc:postgresql://localhost:5432/postgres'
    user: postgres
    password: postgres
  r2dbc:
    url: 'r2dbc:postgresql://postgres:postgres@localhost:5432/postgres'
    pool:
      enabled: true
      initial-size: '5'
      max-size: '10'
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.scheduler:
        instanceName: Scheduler
        instanceId: AUTO
      org.quartz.jobStore:
        dataSource: quartz
        isClustered: true
        class: org.quartz.impl.jdbcjobstore.JobStoreTX
        driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
        tablePrefix: qrtz_
      org.quartz.dataSource:
        quartz:
          driver: org.postgresql.Driver
          provider: hikaricp
          URL: 'jdbc:postgresql://localhost:5432/postgres'
          user: postgres
          password: postgres

logging:
  config: classpath:log4j2.yml